### ISSUE TITLE
Engraved in code transformation.

### ISSUE THREAD

**Issue by mibrl12** [Comcast/eel#108]
Hi. First of all thank you for this project! It is awesome!

From the README:
> The downside is that transformations become engraved in code and cannot be changed easily.

Are there any plans to make transformations updatable (e.g. via HTTP call)?

**Comment by boriwo** [comment]
There is already a /reload API you can call which will reload all handlers from disk. However, there is no API to upload a new handler. Currently you will have to update or add handlers in the file system manually and then either restart eel or call the /reload API to avoid downtime.

**Comment by mibrl12** [comment]
> There is already a /reload API you can call which will reload all handlers from disk. However, there is no API to upload a new handler. Currently you will have to update or add handlers in the file system manually and then either restart eel or call the /reload API to avoid downtime.

Thanks for your prompt reply and the hint. So it is not on the roadmap as of now to make it possible to upload new handlers via API, is it?

**Comment by boriwo** [comment]
We do have an item on our roadmap to support pluggable handler sources, so you could pull handlers from a database, for example, instead of the local file system. But there is no set date when this will be implemented. You are welcome to send us a pull request if you would like to make some changes, for example adding APIs for handler CRUD operations.
